// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: contacts.proto
// Protobuf C++ Version: 5.30.0-dev

#ifndef contacts_2eproto_2epb_2eh
#define contacts_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5030000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_contacts_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_contacts_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_contacts_2eproto;
namespace contacts {
class contact;
struct contactDefaultTypeInternal;
extern contactDefaultTypeInternal _contact_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull contact_class_data_;
}  // namespace contacts
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace contacts {

// ===================================================================


// -------------------------------------------------------------------

class contact final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:contacts.contact) */ {
 public:
  inline contact() : contact(nullptr) {}
  ~contact() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(contact* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(contact));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR contact(
      ::google::protobuf::internal::ConstantInitialized);

  inline contact(const contact& from) : contact(nullptr, from) {}
  inline contact(contact&& from) noexcept
      : contact(nullptr, std::move(from)) {}
  inline contact& operator=(const contact& from) {
    CopyFrom(from);
    return *this;
  }
  inline contact& operator=(contact&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const contact& default_instance() {
    return *internal_default_instance();
  }
  static inline const contact* internal_default_instance() {
    return reinterpret_cast<const contact*>(
        &_contact_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(contact& a, contact& b) { a.Swap(&b); }
  inline void Swap(contact* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(contact* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  contact* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<contact>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const contact& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const contact& from) { contact::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(contact* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "contacts.contact"; }

 protected:
  explicit contact(::google::protobuf::Arena* arena);
  contact(::google::protobuf::Arena* arena, const contact& from);
  contact(::google::protobuf::Arena* arena, contact&& from) noexcept
      : contact(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 2,
    kTelNumberFieldNumber = 3,
    kAddersFieldNumber = 4,
    kIDFieldNumber = 1,
  };
  // string Name = 2;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* value);

  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(
      const std::string& value);
  std::string* _internal_mutable_name();

  public:
  // string TelNumber = 3;
  void clear_telnumber() ;
  const std::string& telnumber() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_telnumber(Arg_&& arg, Args_... args);
  std::string* mutable_telnumber();
  PROTOBUF_NODISCARD std::string* release_telnumber();
  void set_allocated_telnumber(std::string* value);

  private:
  const std::string& _internal_telnumber() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_telnumber(
      const std::string& value);
  std::string* _internal_mutable_telnumber();

  public:
  // string Adders = 4;
  void clear_adders() ;
  const std::string& adders() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_adders(Arg_&& arg, Args_... args);
  std::string* mutable_adders();
  PROTOBUF_NODISCARD std::string* release_adders();
  void set_allocated_adders(std::string* value);

  private:
  const std::string& _internal_adders() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_adders(
      const std::string& value);
  std::string* _internal_mutable_adders();

  public:
  // uint64 ID = 1;
  void clear_id() ;
  ::uint64_t id() const;
  void set_id(::uint64_t value);

  private:
  ::uint64_t _internal_id() const;
  void _internal_set_id(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:contacts.contact)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      44, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const contact& from_msg);
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::internal::ArenaStringPtr telnumber_;
    ::google::protobuf::internal::ArenaStringPtr adders_;
    ::uint64_t id_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_contacts_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull contact_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// contact

// uint64 ID = 1;
inline void contact::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = ::uint64_t{0u};
}
inline ::uint64_t contact::id() const {
  // @@protoc_insertion_point(field_get:contacts.contact.ID)
  return _internal_id();
}
inline void contact::set_id(::uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:contacts.contact.ID)
}
inline ::uint64_t contact::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void contact::_internal_set_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// string Name = 2;
inline void contact::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
}
inline const std::string& contact::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:contacts.contact.Name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void contact::set_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:contacts.contact.Name)
}
inline std::string* contact::mutable_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:contacts.contact.Name)
  return _s;
}
inline const std::string& contact::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void contact::_internal_set_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline std::string* contact::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* contact::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:contacts.contact.Name)
  return _impl_.name_.Release();
}
inline void contact::set_allocated_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:contacts.contact.Name)
}

// string TelNumber = 3;
inline void contact::clear_telnumber() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.telnumber_.ClearToEmpty();
}
inline const std::string& contact::telnumber() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:contacts.contact.TelNumber)
  return _internal_telnumber();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void contact::set_telnumber(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.telnumber_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:contacts.contact.TelNumber)
}
inline std::string* contact::mutable_telnumber() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_telnumber();
  // @@protoc_insertion_point(field_mutable:contacts.contact.TelNumber)
  return _s;
}
inline const std::string& contact::_internal_telnumber() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.telnumber_.Get();
}
inline void contact::_internal_set_telnumber(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.telnumber_.Set(value, GetArena());
}
inline std::string* contact::_internal_mutable_telnumber() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.telnumber_.Mutable( GetArena());
}
inline std::string* contact::release_telnumber() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:contacts.contact.TelNumber)
  return _impl_.telnumber_.Release();
}
inline void contact::set_allocated_telnumber(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.telnumber_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.telnumber_.IsDefault()) {
    _impl_.telnumber_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:contacts.contact.TelNumber)
}

// string Adders = 4;
inline void contact::clear_adders() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.adders_.ClearToEmpty();
}
inline const std::string& contact::adders() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:contacts.contact.Adders)
  return _internal_adders();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void contact::set_adders(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.adders_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:contacts.contact.Adders)
}
inline std::string* contact::mutable_adders() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_adders();
  // @@protoc_insertion_point(field_mutable:contacts.contact.Adders)
  return _s;
}
inline const std::string& contact::_internal_adders() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.adders_.Get();
}
inline void contact::_internal_set_adders(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.adders_.Set(value, GetArena());
}
inline std::string* contact::_internal_mutable_adders() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.adders_.Mutable( GetArena());
}
inline std::string* contact::release_adders() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:contacts.contact.Adders)
  return _impl_.adders_.Release();
}
inline void contact::set_allocated_adders(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.adders_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.adders_.IsDefault()) {
    _impl_.adders_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:contacts.contact.Adders)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace contacts


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // contacts_2eproto_2epb_2eh
