threadpool:threadpool.cc
	g++  $^ -o $@ -std=c++17 -lpthread
package:package.cc
	g++  $^ -o $@ -std=c++11 -lpthread
promise:promise.cc
	g++  $^ -o $@ -std=c++11 -lpthread
Async:Async.cc
	g++  $^ -o $@ -std=c++11 -lpthread